### ISSUE TITLE
Genshin Impact crashes after installation. macOS 11.2.3

### ISSUE THREAD

**Issue by Victorvkk38596** [Letscoder/PlayCover#1]
Play Cover finished the installation of Genshin Impact without any problems. However, it crashes as soon as I launch the game. Check out the crash data attached. The crash happens only when the application is installed with the 'Make fullscreen and add keymapping' option ticked. I reinstalled Genshin Impact with the option unticked, the application launched successfully.
[Genshin Impact Crash Data macOS 11.2.3 Play Cover 0.1.0 (fix).docx](https://github.com/Letscoder/PlayCover/files/6948830/Genshin.Impact.Crash.Data.macOS.11.2.3.Play.Cover.0.1.0.fix.docx)

**Comment by Letscoder** [comment]
Please don’t write issues about old releases, use current Xcode build
