### ISSUE TITLE
Genshin Impact cannot be installed

### ISSUE THREAD

**Issue by simper** [Letscoder/PlayCover#13]
I am with macOS 11.5.2 and PlayCover 0.5.0, downloaded Genshin ipa (2.0) from iMobie APP Checker, ticked "Alternative convert method" and "Export for iOS, Mac (Sideloadly, AltStore)", but then for a while when the ipa is installing, it prompts that app cannot be installed, because it is not intended by developer for the platform, statements like that.
Am I doing something incorrect? Or Genshin Impact is just not supported still?

**Comment by Letscoder** [comment]
Uncheck Export for iOS, Mac (Sideloadly, AltStore), it is for Sideloadly install as writed. If you just want to launch game on Mac you don't need this. And use "Alternative convert method" only, if you have problem with main.

**Comment by Jaedotmoe** [comment]
Getting the exact same problem here on a MacBook Pro M1 16GB, tried with and without the “Alternative convert method” and still gives the same error message.
<img width="275" alt="CleanShot 2021-08-14 at 23 34 26@2x" src="https://user-images.githubusercontent.com/76598503/129459393-40f55212-6142-488c-8139-2dca86e71691.png">
Log is:
```
Creating temp directory
Copying .ipa to temp folder
Unzipping .ipa
Creating entitlements file
IPA is encrypted, trying to decrypt
Creating Wrapper folder
Wrapper path: file:///Users/jae/Documents/PlayCover/temp/1DFB4F71-855C-47B5-AD14-088990DA107C/.app/Wrapper
Copying files
Creating symbolic link
Moving to /Applications 
Success to copy file.
Dump Success
IPA is still encrypted, trying again
Dump Success
Decrypting using alternative way
```
IPA file from iMobie M1 App Checker as well.

**Comment by simper** [comment]
Tried only ticking "Alternative convert method, still the same error and fail to install:
"This application cannot be installed because the developer did not intend for it to run on this platform."
