### ISSUE TITLE
Невозможно установить приложение на этой платформе.

### ISSUE THREAD

**Issue by supersh86** [Letscoder/PlayCover#17]
Добрый день Александр, пытаюсь установить Genshin, использую ipa из imazing. 
При установки выдает ошибку такую же если бы я бы устанавливал игру без PlayCover.
С галками и без, без ранзицы.
Sip не отключен. 

<img width="704" alt="Снимок экрана 2021-08-15 в 22 20 33" src="https://user-images.githubusercontent.com/30050345/129490005-f16e09be-5788-49dc-a5ca-62c8aca23237.png">

PS использую версию для ipad

**Comment by Letscoder** [comment]
[Try to use this .ipa](https://drive.google.com/file/d/1qZohe75wmTP3UIBlQWzuW51UZan4JA5S/view?usp=sharing)
