### ISSUE TITLE
Error has occurred when convert the app which contains white spaces in name

### ISSUE THREAD

**Issue by Ganian** [Letscoder/PlayCover#2]
First of all, thank you for your nice application.

I just tried to convert my own dumped app, but it failed. The app name is "Slay the spire"
I guess the shell execute code in Appcreator.swift can't handle the white space... White space charactor on path needs to be replace.

![image](https://user-images.githubusercontent.com/38222959/128621827-3525f5f0-6461-4d3a-8356-cbbdc27a437e.png)

Could you check about this issue?

**Comment by Letscoder** [comment]
Please, don’t write issues about old releases. Use current Xcode source code to build.

**Comment by Ganian** [comment]
@Letscoder Well... Actually I used current xcode soruce code. It was not an old release.

**Comment by Letscoder** [comment]
Oh, sorry, I'll fix, it is not difficult.
